//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaPolicy) DeepCopyInto(out *ResourceQuotaPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaPolicy.
func (in *ResourceQuotaPolicy) DeepCopy() *ResourceQuotaPolicy {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceQuotaPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaPolicyList) DeepCopyInto(out *ResourceQuotaPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceQuotaPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaPolicyList.
func (in *ResourceQuotaPolicyList) DeepCopy() *ResourceQuotaPolicyList {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceQuotaPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaPolicySpec) DeepCopyInto(out *ResourceQuotaPolicySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaPolicySpec.
func (in *ResourceQuotaPolicySpec) DeepCopy() *ResourceQuotaPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaPolicyStatus) DeepCopyInto(out *ResourceQuotaPolicyStatus) {
	*out = *in
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaPolicyStatus.
func (in *ResourceQuotaPolicyStatus) DeepCopy() *ResourceQuotaPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
